server:
  port: 9077
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  task:
    scheduling:
      pool:
        size: 10
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=Asia/Shanghai&useTimezone=true
    username: postgres
    password: xxxxxxx
    driver-class-name: org.postgresql.Driver
  application:
    name: aiAgent
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  # 全局时区配置
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Shanghai
  # 基础属性配置
  ai:
    chat:
      client:
        enabled: true
      memory:
        repository:
          jdbc:
            initialize-schema: never
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: sk-xxxxxxxxxxxx
      chat:
        options:
          model: qwen3-235b-a22b
      embedding:
        options:
          # 格外注意模型的默认向量维度和创建vector_store_rag表的维度要对应！
          model: text-embedding-v3
        base-url: https://dashscope.aliyuncs.com/compatible-mode
        api-key: sk-xxxxxxxxxxxx
    vectorstore:
      pgvector:
        remove-existing-vector-store-table: false
    mcp:
      client:
        enabled: true
#        type: SYNC
#        stdio:
#          root-change-notification: true
#          connections:
#            server1:
#              command: /path/to/server
#              args:
#                - --port=8080
#                - --mode=production
#              env:
#                API_KEY: your-api-key
#                DEBUG: "true"
        streamable-http:
#          connections:
#            server1:
#              url: http://localhost:8080
#            server2:
#              url: http://otherserver:8081
#              endpoint: /custom-sse
#        sse:
#          connections:
#            # Simple configuration using default /sse endpoint
#            server1:
#              url: http://localhost:8080
#            # Custom SSE endpoint
#            server2:
#              url: http://otherserver:8081
#              sse-endpoint: /custom-sse
#            # Complex URL with path and token (like MCP Hub)
#            mcp-hub:
#              url: http://localhost:3000
#              sse-endpoint: /mcp-hub/sse/cf9ec4527e3c4a2cbb149a85ea45ab01
#            # SSE endpoint with query parameters
#            api-server:
#              url: https://api.example.com
#              sse-endpoint: /v1/mcp/events?token=abc123&format=json
rerank:
  base-url: https://dashscope.aliyuncs.com/api/v1/services/rerank/text-rerank/text-rerank
  api-key: sk-xxxxxxxxxxxx
  model: gte-rerank-v2
image_understanding:
  base-url: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
  api-key: sk-xxxxxxxxxxxx
  model: qwen-vl-plus
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
minio:
  url: http://localhost:9000
  access-key: minio
  secret-key: xxxxxxxx
  img-bucket-name: langhuan-img
  file-bucket-name: langhuan-file
  folder:
    document-img: uploads
    chat-memory-img: chatMemoryImgFold
task:
  schedule:
    documents: 0 0 2 */15 * ?
    image: 0 0 0 * * ?
  lucene:
    cron: 0 0 2 */2 * ?
lucene:
  index-path: ./lucene_index
